### ISSUE TITLE
xmvn-builddep broken in fedora 31+

### ISSUE THREAD

**Issue by decathorpe** [fedora-java/javapackages#74] opened 2019-10-18 20:14 UTC
Running `xmvn-builddep build.log` on fedora 31 results in this crash, regardless of the input file:

```
BuildRequires:  maven-local

gzip: stdin: unexpected end of file
Traceback (most recent call last):
  File "/usr/share/java-utils/builddep.py", line 63, in <module>
    et = etree.parse(args[0]).getroot()
  File "src/lxml/etree.pyx", line 3467, in lxml.etree.parse
  File "src/lxml/parser.pxi", line 1839, in lxml.etree._parseDocument
  File "src/lxml/parser.pxi", line 1865, in lxml.etree._parseDocumentFromURL
  File "src/lxml/parser.pxi", line 1769, in lxml.etree._parseDocFromFile
  File "src/lxml/parser.pxi", line 1163, in lxml.etree._BaseParser._parseDocFromFile
  File "src/lxml/parser.pxi", line 601, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 711, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 640, in lxml.etree._raiseParseError
  File "/dev/stdin", line 1
lxml.etree.XMLSyntaxError: Document is empty, line 1, column 1
```

Manually parsing the MAVEN DEPENDENCIES block yields a valid XML string, so malformed Base64 input / log file is not the issue.

**Comment by decathorpe** [comment] 2019-10-20 14:14
FWIW, it looks like only the shell script is broken.

This quick-n-dirty python3 implementation works fine:
https://gist.github.com/decathorpe/8ceae092f992b1496822034b3ceb9a23

**Comment by mizdebsk** [comment] 2020-07-24 11:22
I'm unable reproduce the issue.
xmvn-builddep shell script is definitely ugly and I agree that it should be rewritten.

**Comment by decathorpe** [comment] 2020-07-24 11:36
I just checked with one package and it seems to work again.
Not sure if it's dependent on the package / build.log contents though ...

**Comment by mizdebsk** [comment] 2020-12-15 09:36
I suspect this could've been a bug in rpm, like https://github.com/rpm-software-management/rpm/pull/818
I'm closing the issues as the problem is no longer reproducible.

**Closed by mizdebsk** 2020-12-15 09:36 UTC
